//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAchi_Library_Management_System {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class FieldSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FieldSettings defaultInstance = ((FieldSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FieldSettings())));
        
        public static FieldSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string itemEntry {
            get {
                return ((string)(this["itemEntry"]));
            }
            set {
                this["itemEntry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string borrowerEntry {
            get {
                return ((string)(this["borrowerEntry"]));
            }
            set {
                this["borrowerEntry"] = value;
            }
        }
    }
}
